### ISSUE TITLE
Can't upload new package directly to checkmk exchange

### ISSUE THREAD

**Issue by virus2500** [tom-mi/python-mkp#1]
Hello,

when i try to upload a package directly to checkmk exchange i get the error message "The structure of the file is invalid".

I noticed while extracting them that when i pack the files using wato there is an additional info.json file which more or less has the same content as the info (without .json) file. Apparently both are necessary. Or at least thats my best guess right now. 

Could you please look into this?

Here you can see both version https://www.dropbox.com/sh/luuqcnlfh5vg07p/AAAun1zadTt7uobvoCmieT30a?dl=0

The one with selfpacked in the name is the one created using your python class. 

Thanks for sharing btw. 👍 

thanks and best regards
Michael

**Comment by tom-mi** [comment]
Hello,

thanks for the report, I didn't have a look at this library for the last 5 years ;)
The `info.json` file is now also added to the archive, containing the same content as `info`.
It worked for one of my mkp packages, please have a look if that solves the problem for you. You'll need version 0.5.

Best regards
Thomas

**Comment by virus2500** [comment]
Hello,

i've seen that it has been quite a while but i thought it couldn't hurt to ask and i wasn't disappointed at all 👍 

It works flawlessly now, thank you very much for the fix!

best regards
Michael.
